import LogbookPendingGroups from './LogbookPendingGroups'
import { isLoggedEntry, entrySubjectLocked } from '../../services/logbookPolicy'
import LogbookCommentBadge from './LogbookCommentBadge'
import { useState } from 'react'
import LogbookPagination from './LogbookPagination'
import { latestEntryEvent, inLastDays } from '../../services/logbookDates'
import { SUBJECTS } from '../../services/logbookCatalog'
import { BookOpen, ChevronDown, ChevronRight, Search } from 'lucide-react'
import { STUDENT, CATEGORIES } from '../../services/logbookSample'
import { entryTitle, facultyName, formatDate, searchEntries } from '../../services/logbook'
import { awaitingRemedial, matchesRemedial } from '../../services/logbookPeople'
import { subjectLabel } from '../../services/logbookCatalog'
import './LogbookViews.css'
import LogbookCategoryMenu from './LogbookCategoryMenu'

/** Presentational collection: all record data and navigation callbacks come from the page. */
export function EntryList({ entries, onOpen, empty = 'No entries here yet.' }) {
  const [limit, setLimit] = useState(25)
  return entries.length ? <div className="lb-entry-list">{entries.slice(0, limit).map((entry) => <button className="lb-entry-row" key={entry.id} onClick={() => onOpen(entry.id)}>
    <span className={`lb-entry-icon is-${entry.status.toLowerCase().replaceAll(' ', '-')}`}><BookOpen size={18} /></span><span className="lb-entry-copy"><span className="lb-title-with-indicators"><strong>{entryTitle(entry)}</strong><LogbookCommentBadge entry={entry} /></span><small>{entry.values.competency ? `${entry.values.competency} · ` : ''}{subjectLabel(entry.subject)} · {facultyName(entry.faculty)}</small></span><span className="lb-entry-meta">{entry.attemptNumber && <small>Attempt {entry.attemptNumber}</small>}<span className={`lb-status is-${entry.status.toLowerCase().replaceAll(' ', '-')}`}>{entry.status}</span><small>{formatDate(entry.date)}</small></span><ChevronRight size={16} />
  </button>)}<LogbookPagination count={entries.length} limit={limit} onMore={() => setLimit(value => value + 25)} /></div> : <div className="lb-empty"><BookOpen size={26} /><p>{empty}</p></div>
}
export function SearchView({ entries, onOpen, view = {}, onFilter, signoffs = [], onSubject }) {
  const { query = '', status = '', category = 'all', subject = '', range = 'all', sort = 'recent' } = view
  const matches = searchEntries(entries, query).filter(entry => (!subject || entry.subject === subject) && (range === 'all' || inLastDays(entry.date, Number(range))) && (!status || (status === 'Logged entries' ? isLoggedEntry(entry) : status === 'Needs action' ? !entrySubjectLocked(entry, signoffs) && (['Draft', 'To do'].includes(entry.status) || (awaitingRemedial(entry, entries) && !entries.some(child => matchesRemedial(entry, child) && child.status === 'Draft'))) : entry.status === status)))
  const options = [{ id: 'all', name: 'All entries', count: matches.length }, ...CATEGORIES.filter(item => !item.legacy || entries.some(entry => entry.cat === item.id)).map(item => ({ ...item, count: matches.filter(entry => entry.cat === item.id).length }))]
  const results = matches.filter(entry => category === 'all' || entry.cat === category).sort((a,b) => (sort === 'oldest' ? a.date.localeCompare(b.date) : sort === 'date' ? b.date.localeCompare(a.date) : latestEntryEvent(b).localeCompare(latestEntryEvent(a))) || a.id.localeCompare(b.id))
  const clear = () => onFilter({ query: '', status: '', category: 'all', subject: '', range: 'all', sort: 'recent' })
  return <div className="lb-search-view"><section className="lb-card lb-filter-toolbar" aria-label="Logbook search and filters">
    <div className="lb-field lb-toolbar-search"><span>Search</span><label className="lb-search"><Search size={18} /><input type="search" aria-label="Search logbook entries" placeholder="Search competency, topic, faculty or feedback" value={query} onChange={event => onFilter({ query: event.target.value })} /></label></div>
    <label className="lb-field">Status<span className="lb-toolbar-select"><select value={status} onChange={event => onFilter({ status: event.target.value })}><option value="">All statuses</option>{['Logged entries', 'Needs action', 'To do', 'Awaiting evaluation', 'Completed', 'Repeat', 'Remedial', 'Draft', 'Pending', 'Approved', 'Returned'].map(value => <option key={value}>{value}</option>)}</select><ChevronDown size={16} aria-hidden="true" /></span></label>
    <label className="lb-field">Subject<span className="lb-toolbar-select"><select value={subject} onChange={event => onFilter({ subject: event.target.value })}><option value="">All subjects</option>{SUBJECTS.map(item => <option key={item.name} value={item.name}>{item.label}</option>)}</select><ChevronDown size={16} aria-hidden="true" /></span></label>
    <label className="lb-field">Activity date<span className="lb-toolbar-select"><select value={range} onChange={event => onFilter({ range: event.target.value })}><option value="all">All dates</option><option value="7">Last 7 calendar days</option><option value="30">Last 30 calendar days</option></select><ChevronDown size={16} aria-hidden="true" /></span></label>
    <label className="lb-field">Sort<span className="lb-toolbar-select"><select value={sort} onChange={event => onFilter({ sort: event.target.value })}><option value="recent">Recent activity</option><option value="date">Newest activity date</option><option value="oldest">Oldest activity date</option></select><ChevronDown size={16} aria-hidden="true" /></span></label><button className="lb-btn lb-clear-filters" onClick={clear}>Clear filters</button></section><div className="lb-all-entries"><LogbookCategoryMenu options={options} value={category} onChange={category => onFilter({ category })} /><section className="lb-card lb-all-entry-results">
    {status === 'Needs action' && signoffs.filter(record => ['Ready', 'Returned'].includes(record.status) && (!subject || record.subject === subject) && (!query || record.subject.toLowerCase().includes(query.toLowerCase()))).map(record => <button className="lb-signoff-row" key={record.subject} onClick={() => onSubject(record.subject)}><strong>{record.subject}</strong><span>Subject approval · {record.status}</span><span>Review final submission</span></button>)}
    <p className="lb-muted" aria-live="polite">{results.length} individual entries found</p><>{status === 'Pending' ? <LogbookPendingGroups entries={results} group={view.group || 'faculty'} onGroup={group => onFilter({ group })} renderEntries={rows => <EntryList entries={rows} onOpen={onOpen} />} /> : <EntryList key={[query,status,subject,category,range,sort].join(':')} entries={results} onOpen={onOpen} empty="No matching entries. Clear filters to see all records." />}</>
  </section></div></div>
}
export function ProfileView({ entries, identity, onReset, busy }) {
  const [confirm, setConfirm] = useState(false)
  const profile = (identity.id || identity.registerId) === STUDENT.registerId ? { ...STUDENT, ...identity } : identity
  return <div className="lb-stack"><section className="lb-card lb-profile"><span className="lb-profile-avatar" aria-hidden="true">{(identity?.name || STUDENT.name).split(' ').map((part) => part[0]).slice(0, 2).join('')}</span><div><span className="lb-eyebrow">Student profile</span><h2>{identity?.name || STUDENT.name}</h2><p>{identity?.registerId || STUDENT.registerId} · {profile.programme || 'Programme not provided'}{profile.batch ? ` · Batch ${profile.batch}` : ''}</p><p className="lb-muted">{profile.posting ? `${profile.posting} posting` : 'Posting not provided'}{profile.postingEnd ? ` · ends ${formatDate(profile.postingEnd)}` : ''}</p></div></section><div className="lb-metrics">{['Approved', 'Pending', 'Returned'].map((status) => <div className="lb-metric" key={status}><span>{status} entries</span><strong>{entries.filter((entry) => entry.status === status).length}</strong></div>)}</div><section className="lb-card"><h2>Faculty interactions</h2><p className="lb-muted">Submitted entries grouped by their verifying faculty.</p>{[...new Set(entries.filter((entry) => entry.faculty && entry.status !== 'Draft').map((entry) => entry.faculty))].map((id) => <div className="lb-profile-row" key={id}><span>{facultyName(id)}</span><strong className="lb-mono">{entries.filter((entry) => entry.faculty === id && entry.status !== 'Draft').length} entries</strong></div>)}</section><section className="lb-card"><h2>Reset sample Logbook</h2><p className="lb-muted">Restore your sample records and remove your entry changes and final approvals from this browser. Other students and approval-chain settings are kept.</p>{confirm ? <div className="lb-actions" role="alert"><strong>Reset entries and final approvals for this student? Other students will be kept.</strong><button className="lb-btn" disabled={busy} onClick={() => setConfirm(false)}>Cancel</button><button className="lb-btn" disabled={busy} onClick={async () => { await onReset(); setConfirm(false) }}>{busy ? 'Resetting…' : 'Confirm reset'}</button></div> : <button className="lb-btn" onClick={() => setConfirm(true)}>Reset Logbook data</button>}</section></div>
}
