import { matchesAdminSearch } from '../services/logbookAdminSearch'
import { subjectCategory } from '../services/logbookSubjectGroups'
import AdminLogbookSignoffs from '../components/logbook/AdminLogbookSignoffs'
import AdminLogbookSubjectDetail from '../components/logbook/AdminLogbookSubjectDetail'
import { subjectWriteBlock } from '../services/logbookPolicy'
import LogbookAccountSwitcher from '../components/logbook/LogbookAccountSwitcher'
import LogbookStorageRecovery from '../components/logbook/LogbookStorageRecovery'
import { LogbookReaderContext } from '../services/logbookCommentRead'
import AdminStudentEntryGroups from '../components/logbook/AdminStudentEntryGroups'
import AdminLogbookStudentDetail from '../components/logbook/AdminLogbookStudentDetail'
import AdminLogbookQuickSearch from '../components/logbook/AdminLogbookQuickSearch'
import AdminLogbookCategoryDetail from '../components/logbook/AdminLogbookCategoryDetail'
import AdminLogbookDashboard from '../components/logbook/AdminLogbookDashboard'
import AdminLogbookSkills from '../components/logbook/AdminLogbookSkills'
import '../components/logbook/AdminLogbookQueue.css'
import AdminLogbookStudents from '../components/logbook/AdminLogbookStudents'
import { categoryLabel } from '../services/logbookPresentation'
import { useEffect, useRef, useState } from 'react'
import LogbookConfirm from '../components/logbook/LogbookConfirm'
import { inLastDays } from '../services/logbookDates'
import { BookOpen, ChevronDown, ChevronRight, Plus, Search, LayoutDashboard, Clock3, Users, Layers, CheckCircle2, FilePenLine, Undo2 } from 'lucide-react'
import PageNavigationHeader from '../components/PageNavigationHeader'
import LogbookBoundary from '../components/logbook/LogbookBoundary'
import LogbookEntryDetail from '../components/logbook/LogbookEntryDetail'
import AdminLogbookRecords from '../components/logbook/AdminLogbookRecords'
import AdminLogbookHistory from '../components/logbook/AdminLogbookHistory'
import AdminLogbookSubjects from '../components/logbook/AdminLogbookSubjects'
import { AssignmentDrawer, ApprovalChain, SignoffList } from '../components/logbook/LogbookFacultyActions'
import { closeLogbookDrawer } from '../components/logbook/closeLogbookDrawer'
import { listLogbookEntries, STORAGE_KEY, today } from '../services/logbook'
import { cancelAssignment, changeSignoff, chainFor, getLogbookWorkflow, reviewEntries } from '../services/adminLogbook'
import { actionable, learnerRegisterId, waitingDays, REVIEWERS, awaitingRemedial, belongsTo, isGraded, LEARNERS, learnerName, overdueEntry, visibleTo } from '../services/logbookPeople'
import { learnerSummary } from '../services/logbookProgress'
import { ADMIN_LOGBOOK_SECTIONS } from '../services/useAdminLogbookRoute'
import { SUBJECTS } from '../services/logbookSample'
import AdminLogbookCategories from '../components/logbook/AdminLogbookCategories'
import '../styles/medsy/question-sort-tokens.css'
import '../styles/ospe-activity.css'
import '../styles/my-skills.css'
import './LogbookPage.css'
import '../components/logbook/LogbookDashboard.css'
import '../components/logbook/LogbookStatus.css'
import './AdminLogbookPage.css'

import '../components/logbook/LogbookPolish.css'
import '../components/logbook/LogbookReadability.css'

/** The shell provides the account and URL state. All counts derive from shared records. */
function AdminLogbookContent({ theme, actor, view, onNavigate, onSelectActor, history: navigationHistory }) {
  const [entries, setEntries] = useState([]), [workflow, setWorkflow] = useState(null)
  const [selectedId, setSelectedId] = useState(null), [checked, setChecked] = useState([])
  const [assignment, setAssignment] = useState(null), [comments, setComments] = useState({})
  const [notice, setNotice] = useState(''), [error, setError] = useState(''), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [reload, setReload] = useState(0)
  const [confirmation, setConfirmation] = useState(null)
  const selectAll = useRef(null)
  const office = !actor.departments.length
  const sections = office ? ADMIN_LOGBOOK_SECTIONS.filter(name => ['Overview', 'Subjects', 'Sign-offs', 'Search'].includes(name)) : ADMIN_LOGBOOK_SECTIONS
  const section = sections.includes(view.section) ? view.section : 'Overview'
  const { id: drill, query = '', status = '', category = '', range = 'all', show = 'all', subject = '' } = view
  useEffect(() => {
    let active = true
    const refresh = async () => { try { const [rows, state] = await Promise.all([listLogbookEntries(), getLogbookWorkflow()]); if (active) { setEntries(rows); setWorkflow(state); setError('') } } catch (failure) { if (active) setError(failure.message) } finally { if (active) setLoading(false) } }
    const storage = event => { if (!event.key || event.key === STORAGE_KEY) void refresh() }
    void refresh(); window.addEventListener('medsy-logbook-changed', refresh); window.addEventListener('storage', storage)
    return () => { active = false; window.removeEventListener('medsy-logbook-changed', refresh); window.removeEventListener('storage', storage) }
  }, [reload])
  const navigate = (name, id = '', filters = {}) => { setChecked([]); onNavigate({ section: name, id, ...filters }) }
  const filter = patch => { if (busy) return; setChecked([]); onNavigate({ ...view, ...patch }, true) }
  const run = async operation => { setBusy(true); setError(''); try { await operation(); setNotice('Changes saved.'); setChecked([]) } catch (failure) { setError(failure.message) } finally { setBusy(false) } }
  const visible = entries.filter(visibleTo)
  const department = office ? visible : visible.filter(entry => actor.departments.includes(entry.subject))
  const pending = visible.filter(entry => actionable(entry, actor) && !subjectWriteBlock(workflow, entry.studentId || 'MC2568', entry.subject)).sort((a, b) => (a.submittedAt || a.date).localeCompare(b.submittedAt || b.date))
  const selected = visible.find(entry => entry.id === selectedId)
  const signoffs = Object.values(workflow?.signoffs || {}).filter(record => actor.departments.includes(record.subject) || (record.chain || []).includes(actor.id))
  const mySignoffs = signoffs.filter(record => record.status === 'Submitted' && record.chain[record.step] === actor.id)
  const students = LEARNERS.map(student => ({ ...student, ...learnerSummary(student.id, entries, actor.departments) }))
  const outstanding = department.filter(entry => entry.faculty === actor.id && isGraded(entry) && awaitingRemedial(entry, entries))
  const tasks = department.filter(entry => entry.status === 'To do' && entry.assignment?.by === actor.id)
  const allHistory = visible.flatMap(entry => (entry.audit || []).filter(event => event.actor === actor.id && ['Approved', 'Returned'].includes(event.action)).map((event, index) => ({ entry, event, key: entry.id + index }))).sort((a, b) => b.event.at.localeCompare(a.event.at))
  const certifiedEvents = allHistory.filter(item => item.event.action === 'Approved' && isGraded(item.entry) && inLastDays(item.event.at, 7))
  const certifiedWeek = certifiedEvents.length
  const history = show === 'certified' ? certifiedEvents : allHistory
  const searchIdle = section === 'Search' && !query.trim() && !status && !category && range === 'all' && show === 'all' && !subject
  let source = section === 'Queue' ? pending : ['Subjects', 'Search'].includes(section) ? visible : department
  if (section === 'Subjects' && view.studentId) source = source.filter(entry => belongsTo(entry, view.studentId))
  if (drill) source = source.filter(entry => section === 'Students' ? belongsTo(entry, drill) : section === 'Subjects' ? entry.subject === drill : subjectCategory(entry) === (drill === 'remedial' ? 'cert' : drill))
  const results = searchIdle ? [] : source.filter(entry => (!view.skill || (entry.values.competency || entry.values.activity) === view.skill) && (!subject || entry.subject === subject) && (!status || entry.status === status) && (section === 'Subjects' || !category || subjectCategory(entry) === (category === 'remedial' ? 'cert' : category)) && (range === 'all' || inLastDays(entry.submittedAt || entry.date, Number(range))) && (show !== 'overdue' || overdueEntry(entry)) && (show !== 'remedial' || Boolean(entry.linkedTo)) && (show !== 'todo' || entry.status === 'To do') && (show !== 'assigned' || entry.assignment?.by === actor.id) && (show !== 'outstanding' || (entry.faculty === actor.id && isGraded(entry) && awaitingRemedial(entry, entries))) && matchesAdminSearch(entry, query)).sort((a, b) => section === 'Queue' ? (a.submittedAt || a.date).localeCompare(b.submittedAt || b.date) : (b.submittedAt || b.date).localeCompare(a.submittedAt || a.date))
  const eligible = results.filter(entry => actionable(entry, actor) && !subjectWriteBlock(workflow, entry.studentId || 'MC2568', entry.subject) && !isGraded(entry)).map(entry => entry.id)
  const selectedIds = checked.filter(id => eligible.includes(id))
  useEffect(() => { if (selectAll.current) selectAll.current.indeterminate = selectedIds.length > 0 && selectedIds.length < eligible.length }, [selectedIds.length, eligible.length])
  const cancel = entry => { if (entry.assignment?.by !== actor.id) return; setConfirmation({ title: 'Cancel this unsubmitted assignment?', description: entry.values.activity || entry.values.topic || entry.subject, action: () => cancelAssignment(entry.id, actor) }) }
  const list = (rows, selectable = false) => <AdminLogbookRecords busy={busy} grouped={section === 'Queue'} subjectRows={section === 'Subjects'} rows={rows} actorId={actor.id} empty={searchIdle ? 'Search by student, registration, subject, activity or feedback.' : 'No entries in this view.'} onOpen={setSelectedId} eligible={selectable ? eligible : []} checked={selectedIds} onCheck={(id, value) => setChecked(value ? [...checked, id] : checked.filter(item => item !== id))} onCancel={rows.some(entry => entry.status === 'To do' && entry.assignment?.by === actor.id) ? cancel : undefined} />
  const filters = <fieldset disabled={busy} className="admin-filters faculty-fieldset"><label className="lb-search"><Search size={16} /><input type="search" aria-label="Search student entries" placeholder="Search student, registration, activity or feedback" value={query} onChange={event => filter({ query: event.target.value })} /></label>{!['Queue', 'Categories'].includes(section) && <span className="admin-filter-select"><select aria-label="Status" value={status} onChange={event => filter({ status: event.target.value })}><option value="">All statuses</option>{['To do', 'Pending', 'Approved', 'Returned'].map(value => <option key={value}>{value}</option>)}</select><ChevronDown size={16} aria-hidden="true" /></span>}{!['Categories', 'Subjects'].includes(section) && <span className="admin-filter-select"><select aria-label="Category" value={category} onChange={event => filter({ category: event.target.value })}><option value="">All categories</option>{[...new Set(source.map(subjectCategory))].map(id => <option key={id} value={id}>{categoryLabel(id)}</option>)}</select><ChevronDown size={16} aria-hidden="true" /></span>}<span className="admin-filter-select"><select aria-label="Submitted date range" value={range} onChange={event => filter({ range: event.target.value })}><option value="all">Any time</option><option value="7">Last 7 days</option><option value="30">Last 30 days</option></select><ChevronDown size={16} aria-hidden="true" /></span>{section === 'Queue' && <span className="admin-filter-select"><select aria-label="Show queue" value={show} onChange={event => filter({ show: event.target.value })}><option value="all">Everything waiting</option><option value="overdue">Overdue</option><option value="remedial">Remedial re-attempts</option></select><ChevronDown size={16} aria-hidden="true" /></span>}{section === 'Search' && <label className="lb-field">Subject<select aria-label="Filter entries by subject" value={subject} onChange={event => filter({ subject: event.target.value })}><option value="">All subjects</option>{SUBJECTS.map(item => <option key={item.name} value={item.name}>{item.label}</option>)}</select></label>}<button className="lb-btn" onClick={() => filter({ query: '', status: '', category: '', subject: '', range: 'all', show: 'all' })}>Clear</button></fieldset>
  const student = students.find(person => person.id === drill)
  const signoffProps = { actor, entries, theme, workflow, onChanged: setNotice, onOpenLogbook: (studentId, subject) => navigate('Subjects', subject, { studentId, query: '', status: '', category: '', range: 'all', show: 'all', subject: '', returnApproval: `${studentId}:${subject}` }) }
  const metrics = office ? [
    ['Awaiting your signature', mySignoffs.length, FilePenLine, () => navigate('Sign-offs', '', { approvalStatus: 'mine', approval: '' })],
    ['With other approvers', signoffs.filter(record => record.status === 'Submitted' && record.chain[record.step] !== actor.id).length, Clock3, () => navigate('Sign-offs', '', { approvalStatus: 'others', approval: '' })],
    ['Completed logbooks', signoffs.filter(record => record.status === 'Completed').length, CheckCircle2, () => navigate('Sign-offs', '', { approvalStatus: 'Completed', approval: '' })],
    ['Subjects', SUBJECTS.length, Layers, () => navigate('Subjects')],
  ] : [
    ['Waiting for you', pending.length, Clock3, () => navigate('Queue', '', { query: '', category: '', range: 'all', show: 'all' })],
    ['Overdue', pending.filter(overdueEntry).length, Clock3, () => navigate('Queue', '', { show: 'overdue', query: '', category: '', range: 'all' })],
    ['Awaiting remedial', outstanding.length, Undo2, () => navigate('Search', '', { status: 'Returned', show: 'outstanding', query: '', category: '', subject: '', range: 'all' })],
    ['Skill attempts approved · last 7 days', certifiedWeek, CheckCircle2, () => navigate('History', '', { show: 'certified', historySubject: '', historyStudent: '', historyDecision: '', historyRange: '' })],
    ['Awaiting your signature', mySignoffs.length, FilePenLine, () => navigate('Sign-offs')],
    ['Assigned to do', tasks.length, BookOpen, () => navigate('Search', '', { status: 'To do', show: 'assigned', query: '', category: '', subject: '', range: 'all' })],
  ]
  const metricDetails = office ? [] : [pending.length ? `${new Set(pending.map(entry => entry.studentId || 'MC2568')).size} students / Longest wait ${Math.max(...pending.map(waitingDays))} days` : 'Your queue is clear', `${new Set(pending.filter(overdueEntry).map(entry => entry.studentId || 'MC2568')).size} students affected`, `${new Set(outstanding.map(entry => entry.studentId || 'MC2568')).size} students need follow-up`, `${allHistory.filter(item => item.event.action === 'Approved' && isGraded(item.entry)).length} approved attempts in total`, 'Final subject approval', `${tasks.filter(entry => entry.assignment?.due && entry.assignment.due < today()).length} assignments past due`]
  return <section className={`vx-content ospe-page my-skills-page logbook-scope lb-page admin-logbook-page ${section !== 'Overview' ? 'lb-working-view' : ''}`}><div className="ospe-shell my-skills-shell lb-shell admin-logbook-shell">
    <div className="lb-admin-navigation-row"><PageNavigationHeader onBack={navigationHistory.back} onForward={navigationHistory.forward} canBack={navigationHistory.canBack} canForward={navigationHistory.canForward} items={['My Pages', { label: 'Admin logbook', onClick: () => navigate('Overview') }, ...(section === 'Overview' ? [] : [{ label: section, onClick: () => navigate(section) }]), ...(drill ? [section === 'Students' ? learnerName(drill) : section === 'Categories' ? categoryLabel(drill) : drill] : [])]} /><LogbookAccountSwitcher actor={actor} onSelect={onSelectActor} disabled={busy} /></div>
    <header className="my-skills-overview lb-page-head admin-page-head"><div className="my-skills-overview-main"><span className="ospe-kicker">Faculty logbook</span><div className="my-skills-overview-copy"><h1>Admin logbook</h1><p>{actor.name}{actor.role === 'Faculty' ? ` · ${actor.departments.join(' / ')}` : actor.name !== actor.role ? ` · ${actor.role}` : ''}</p><p>Review learning experiences and guide students towards completion.</p></div></div><div className="my-skills-live-card lb-create-card admin-action-card"><div className="my-skills-live-card-top"><span className="my-skills-live-indicator"><BookOpen size={15} />Faculty review</span></div><div className="my-skills-live-card-body"><strong>{office ? 'Complete final approvals' : 'Guide the next learning experience'}</strong><p>{office ? 'Review subject logbooks awaiting your signature.' : 'Assign an activity and support students through verification.'}</p></div><button className="tool-btn my-skills-live-card-cta lb-new-entry-btn" disabled={loading} onClick={() => office ? navigate('Sign-offs') : setAssignment({ studentId: section === 'Students' ? drill : '' })}><Plus size={16} />{office ? 'Review sign-offs' : 'Assign logbook entry'}</button></div></header>
    <nav className="lb-navigation admin-tabs" aria-label="Admin Logbook sections">{sections.map(name => { const Icon = { Overview: LayoutDashboard, Queue: Clock3, Students: Users, Subjects: Layers, Categories: Layers, Skills: CheckCircle2, History: Clock3, 'Sign-offs': FilePenLine, Search }[name]; return <button key={name} className={'my-skills-filter-chip' + (section === name ? ' is-active' : '')} aria-current={section === name ? 'page' : undefined} onFocus={event => event.currentTarget.scrollIntoView({ block: 'nearest', inline: 'nearest' })} onClick={() => navigate(name)}><Icon size={15} />{name === 'Overview' ? 'Dashboard' : name}{name === 'Queue' && <span className="admin-tab-count">{pending.length}</span>}</button> })}</nav>

    {confirmation && <LogbookConfirm title={confirmation.title} busy={busy} onCancel={() => setConfirmation(null)} onConfirm={async () => { await run(confirmation.action); setConfirmation(null) }}><p>{confirmation.description}</p></LogbookConfirm>}{notice && <div className="lb-alert" role="status">{notice}<button className="lb-btn" onClick={() => setNotice('')}>Dismiss</button></div>}{error && <div className="lb-alert lb-error" role="alert">{error}<LogbookStorageRecovery message={error} /><button className="lb-btn" onClick={() => setReload(value => value + 1)}>Reload</button></div>}
    {loading ? <p role="status">Loading records...</p> : <>
      {section === 'Overview' && <div className="faculty-dashboard"><AdminLogbookQuickSearch entries={visible} onOpen={setSelectedId} onViewAll={filters => navigate('Search', '', filters)} /><div className="lb-summary-strip admin-logbook-metrics" data-count={metrics.length}>{metrics.map(([label, count, icon, go], index) => { const MetricIcon = icon; return <button key={label} className={'lb-summary-item my-skills-metric-card ' + (index < 2 ? 'is-assigned' : 'is-completed')} onClick={go}><span className="my-skills-metric-card-icon"><MetricIcon size={18} /></span><span className="my-skills-metric-card-copy"><strong>{count}</strong><span>{label}</span>{metricDetails[index] && <small>{metricDetails[index]}</small>}</span></button> })}</div><AdminLogbookDashboard entries={department} signoffs={signoffs} navigate={navigate} /><div className="admin-overview-grid"><section className="lb-card"><div className="lb-section-head"><h2>{office ? 'Awaiting your signature' : 'Longest waiting'}</h2><button className="lb-text-btn" onClick={() => navigate(office ? 'Sign-offs' : 'Queue')}>View all</button></div>{office ? <SignoffList {...signoffProps} records={mySignoffs} /> : list(pending.slice(0, 4))}</section>{!office && <section className="lb-card"><div className="lb-section-head"><h2>Students needing attention</h2><button className="lb-text-btn" onClick={() => navigate('Students', '', { show: 'risk' })}>View all</button></div>{!students.some(person => person.risk) && <p className="lb-empty">No students need follow-up.</p>}{students.filter(person => person.risk).slice(0, 5).map(person => <button className="admin-tile" key={person.id} onClick={() => navigate('Students', person.id)}><strong>{person.name}</strong><small>{person.required ? `${person.met}/${person.required} logged category targets met` : 'Category targets not configured'} | {person.returned} returned</small><ChevronRight size={16} /></button>)}<p className="lb-muted">{tasks.filter(entry => entry.assignment?.due && entry.assignment.due < today()).length} assigned tasks past due</p></section>}</div></div>}
      {section === 'Students' && !drill && <AdminLogbookStudents sort={view.sort} students={students} query={query} show={show} onFilter={filter} onOpen={id => navigate('Students', id)} />}
      {section === 'Subjects' && !drill && <AdminLogbookSubjects departments={actor.departments} entries={visible} onSubject={subject => navigate('Subjects', subject)} />}
      {section === 'Categories' && !drill && <AdminLogbookCategories subjects={actor.departments} entries={department} onCategory={category => navigate('Categories', category)} />}
      {drill && !['Categories', 'Students'].includes(section) && <button className="lb-btn admin-back" onClick={() => navigate(section)}>Back to {section.toLowerCase()}</button>}
      {section === 'Students' && view.skill && <section className="lb-card lb-section-head"><p>Reviewing {subject} / {view.skill}</p><button className="lb-btn" onClick={() => navigate('Skills', '', { subject, query: view.skill })}>Back to skill</button><button className="lb-btn" onClick={() => filter({ skill: '' })}>All student entries</button></section>}
      {section === 'Students' && drill && !student && <section className="lb-card lb-empty"><h2>Student unavailable</h2><p>This student is not in the current cohort.</p><button className="lb-btn" onClick={() => navigate('Students')}>Back to students</button></section>}{section === 'Students' && student && <AdminLogbookStudentDetail selectedSubject={subject} student={student} subjects={subject ? actor.departments.filter(item => item === subject) : actor.departments} workflow={workflow} busy={busy} onBack={() => navigate('Students')} onAssign={() => setAssignment({ studentId: student.id, subject })} onReady={subject => run(() => changeSignoff({ studentId: student.id, subject, actor, action: 'ready' }))} renderSignoff={record => <SignoffList {...signoffProps} records={[record]} />} />}
      {section === 'Subjects' && drill && <section className="lb-card lb-stack"><h2>{drill}</h2><p className="lb-muted">{SUBJECTS.find(item => item.name === drill)?.phase} / {REVIEWERS.filter(person => person.departments.includes(drill)).length} faculty members</p><p className="lb-muted">{actor.departments.includes(drill) ? 'Your department. Only entries addressed to you can be reviewed.' : 'Read-only review. You can comment; the addressed faculty verifies entries.'}</p><div className="admin-progress-summary"><span>{source.filter(entry => entry.status !== 'To do').length} entries</span><span>{new Set(source.filter(entry => entry.status !== 'To do').map(entry => entry.studentId || 'MC2568')).size} students</span><span>{source.filter(entry => entry.status === 'Pending').length} pending</span><span>{source.filter(entry => entry.status === 'Approved').length} approved</span></div>{workflow && actor.departments.includes(drill) && <ApprovalChain key={drill + chainFor(workflow, drill).join('-')} chain={chainFor(workflow, drill)} subject={drill} actor={actor} onChanged={setNotice} />}</section>}
      {(['Queue', 'Search'].includes(section) || (drill && section === 'Students' && student)) && <section className={'lb-card lb-stack' + (section === 'Queue' ? ' admin-review-queue' : section === 'Students' ? ' admin-student-entries' : '')}>{section === 'Queue' && <header><h2>Approval queue</h2><p className="lb-muted">{results.length} entries / {new Set(results.map(entry => entry.studentId || 'MC2568')).size} students / {results.filter(overdueEntry).length} overdue / Oldest first</p></header>}{!['Queue', 'Students'].includes(section) && <h2>{section === 'Search' ? 'Search entries' : 'Entries'}</h2>}{section === 'Search' && subject && <p className="lb-muted">Subject: {subject}</p>}{show === 'outstanding' && <p className="lb-muted">Returned skills awaiting a submitted remedial attempt.</p>}{show === 'assigned' && <p className="lb-muted">Unsubmitted assignments created by you.</p>}{filters}{section !== 'Students' && <p className="lb-muted" aria-live="polite">{searchIdle ? 'Find entries across all subjects' : results.length + ' entries'}{section === 'Queue' ? ' awaiting review / Oldest first' : ''}</p>}
        {section === 'Queue' && eligible.length > 0 && <div className="lb-actions"><label><input type="checkbox" ref={selectAll} disabled={busy} aria-checked={selectedIds.length > 0 && selectedIds.length < eligible.length ? 'mixed' : selectedIds.length === eligible.length} checked={selectedIds.length === eligible.length} onChange={event => setChecked(event.target.checked ? eligible : [])} /> Select eligible entries</label><button className="lb-btn lb-primary" disabled={busy || !selectedIds.length} onClick={() => { setConfirmation({ title: `Approve ${selectedIds.length} entries?`, description: 'All selected entries will be approved. Skills requiring grades are excluded.', action: () => reviewEntries([...selectedIds], actor, { status: 'Approved' }) }) }}>Approve selected ({selectedIds.length})</button><small>Skills are graded individually.</small></div>}
        {section === 'Queue' ? [...new Set(results.map(entry => entry.studentId || 'MC2568'))].map(id => { const rows = results.filter(entry => belongsTo(entry, id)); return <section className="admin-queue-group" key={id}><div className="admin-group-heading"><button className="lb-text-btn" onClick={() => navigate('Students', id)}><span className="admin-queue-avatar" aria-hidden="true">{learnerName(id).split(' ').map(part => part[0]).slice(0, 2).join('')}</span><strong>{learnerName(id)}</strong><span className="admin-queue-id">{learnerRegisterId(id)}</span></button><small>{rows.length} waiting / Longest wait {Math.max(...rows.map(waitingDays))} days</small></div>{list(rows, true)}</section> }) : section === 'Students' ? <AdminStudentEntryGroups rows={results} renderEntries={list} /> : list(results)}
        {['Queue', 'Students', 'Subjects'].includes(section) && !results.length && <p className="lb-empty">{query || category || status || show !== 'all' ? 'No entries match these filters.' : 'No entries in this view.'}</p>}
      </section>}
      {section === 'Subjects' && drill && <section className="lb-card lb-stack"><h2>Student subject approvals</h2>{view.studentId && <p className="lb-muted">Reviewing {learnerName(view.studentId)} / {learnerRegisterId(view.studentId)} / {drill}</p>}{view.returnApproval && <button className="lb-btn" onClick={() => navigate('Sign-offs', '', { approval: view.returnApproval, approvalStatus: '', approvalSubject: '', approvalStudent: '' })}>Return to approval</button>}{LEARNERS.filter(person => view.studentId ? person.id === view.studentId : source.some(entry => belongsTo(entry, person.id))).map(person => { const approval = workflow?.signoffs?.[person.id + ':' + drill]; return <div className="lb-section-head" key={person.id}><span>{person.name} / {learnerRegisterId(person.id)} <small>{approval?.status || 'Not ready'}</small></span><button className="lb-btn" onClick={() => approval ? navigate('Sign-offs', '', { approval: person.id + ':' + drill, approvalStatus: '', approvalSubject: '', approvalStudent: '' }) : navigate('Students', person.id, { subject: drill, query: '', category: '', status: '', range: 'all', show: 'all' })} disabled={!approval && !actor.departments.includes(drill)}>{approval ? 'View approval' : 'Review readiness'}</button></div> })}</section>}
      {section === 'Subjects' && drill && <AdminLogbookSubjectDetail key={drill} source={source} rows={results} category={category === 'remedial' ? 'cert' : category} onCategory={value => filter({ category: value })} filters={filters} renderEntries={list} />}
      {section === 'Categories' && drill && <AdminLogbookCategoryDetail category={drill} entries={source} results={results} status={status} filters={filters} onBack={() => navigate('Categories')} onStatus={value => filter({ status: value })} renderEntries={list} />}
      {section === 'Skills' && <AdminLogbookSkills view={view} onFilter={filter} subjects={actor.departments} department={department} entries={entries} onStudent={(id, subject, skill) => navigate('Students', id, { subject, skill, query: '', status: '', category: '', range: 'all', show: 'all' })} renderEntries={list} />}
      {section === 'History' && <AdminLogbookHistory view={view} onFilter={filter} history={history} certified={show === 'certified'} onShowAll={() => navigate('History', '', { show: 'all' })} onOpen={setSelectedId} />}
      {section === 'Sign-offs' && <AdminLogbookSignoffs {...signoffProps} records={signoffs} view={view} onFilter={filter} />}
    </>}
    {assignment && <AssignmentDrawer {...assignment} workflow={workflow} actor={actor} theme={theme} onChanged={setNotice} onClose={() => { void closeLogbookDrawer(() => setAssignment(null)) }} />}
    {selected && <LogbookEntryDetail key={selected.id} entry={selected} workflow={workflow} entries={visible} theme={theme} role="faculty" actor={actor} commentDraft={comments[selected.id] || ''} onCommentDraft={text => setComments(current => ({ ...current, [selected.id]: text }))} onOpen={setSelectedId} onChanged={setNotice} onClose={() => { void closeLogbookDrawer(() => setSelectedId(null)) }} />}
  </div></section>
}
export default function AdminLogbookPage(props) { return <LogbookBoundary><LogbookReaderContext.Provider value={{ id: props.actor.id, name: props.actor.name, role: 'faculty' }}><AdminLogbookContent {...props} /></LogbookReaderContext.Provider></LogbookBoundary> }
